import { MD3LightTheme } from "react-native-paper";

const baseLightThemeProps = {
  ...MD3LightTheme,
};

const errorColors = {
  error: "#F4B2B2",
  onError: "#4B2020",
  errorContainer: "#FDE1E1",
  onErrorContainer: "#2C1B1B",
};

const createLightTheme = (customColors: Object) => {
  return {
    ...baseLightThemeProps,
    colors: {
      ...MD3LightTheme.colors,
      ...customColors,
      ...errorColors,
      shadow: '#000000',
      scrim: '#000000',
    },
  };
};

export const greenPastelLightTheme = createLightTheme({
  primary: "#A8D5BA",
  onPrimary: "#1D2E25",
  primaryContainer: "#DFF5E1",
  onPrimaryContainer: "#102018",
  secondary: "#B3DAC6",
  onSecondary: "#1F2E27",
  secondaryContainer: "#E1F7EA",
  onSecondaryContainer: "#102017",
  tertiary: "#AED9C4",
  onTertiary: "#203229",
  tertiaryContainer: "#DCF4E9",
  onTertiaryContainer: "#11201A",
  background: "#FAFDFB",
  onBackground: "#1C1B1F",
  surface: "#F9FCFA",
  onSurface: "#1C1B1F",
  surfaceVariant: "#DDEDE4",
  onSurfaceVariant: "#404942",
  outline: "#7A8F85",
  inverseSurface: "#2F312F",
  inverseOnSurface: "#EFF3F0",
  inversePrimary: "#7EB89C",
  surfaceTint: "#A8D5BA",
  outlineVariant: "#C1D5CA",
});

export const pinkPastelLightTheme = createLightTheme({
  primary: "#F2AFC3",
  onPrimary: "#3A1E28",
  primaryContainer: "#FCE3EB",
  onPrimaryContainer: "#2A1017",
  secondary: "#F5C1D1",
  onSecondary: "#3A1F29",
  secondaryContainer: "#FDE7EF",
  onSecondaryContainer: "#2B1119",
  tertiary: "#E8A9BE",
  onTertiary: "#351D27",
  tertiaryContainer: "#FBE2EB",
  onTertiaryContainer: "#260E16",
  background: "#FFF8FA",
  onBackground: "#1E1B1C",
  surface: "#FFFAFC",
  onSurface: "#1E1B1C",
  surfaceVariant: "#EAD3DB",
  onSurfaceVariant: "#4B3B42",
  outline: "#8A6F79",
  outlineVariant: "#D7C2C8",
  surfaceTint: "#F2AFC3",
  inverseSurface: "#322F30",
  inverseOnSurface: "#FCE9ED",
  inversePrimary: "#D88EA5",
});

// Faça o mesmo para os demais temas light:

export const redPastelLightTheme = createLightTheme({
  primary: "#F28C8C",
  onPrimary: "#3C1010",
  primaryContainer: "#FCDCDC",
  onPrimaryContainer: "#2C0A0A",
  secondary: "#F5A5A5",
  onSecondary: "#3B1A1A",
  secondaryContainer: "#FEE5E5",
  onSecondaryContainer: "#2A0F0F",
  tertiary: "#E88D8D",
  onTertiary: "#351212",
  tertiaryContainer: "#FBDADA",
  onTertiaryContainer: "#250B0B",
  background: "#FFF7F7",
  onBackground: "#1E1B1B",
  surface: "#FFF9F9",
  onSurface: "#1E1B1B",
  surfaceVariant: "#E6C1C1",
  onSurfaceVariant: "#4C3A3A",
  outline: "#8C6D6D",
  outlineVariant: "#D7BCBC",
  surfaceTint: "#F28C8C",
  inverseSurface: "#322F2F",
  inverseOnSurface: "#FCE9E9",
  inversePrimary: "#DA6E6E",
});

export const yellowPastelLightTheme = createLightTheme({
  primary: "#F2D28C",
  onPrimary: "#3C2F0F",
  primaryContainer: "#FFF5D5",
  onPrimaryContainer: "#2F230A",
  secondary: "#F4E2A5",
  onSecondary: "#3B310F",
  secondaryContainer: "#FFF7D6",
  onSecondaryContainer: "#2A2309",
  tertiary: "#E8C88D",
  onTertiary: "#352A10",
  tertiaryContainer: "#FFF0D4",
  onTertiaryContainer: "#251D08",
  background: "#FFFCF5",
  onBackground: "#1C1B18",
  surface: "#FFFCF5",
  onSurface: "#1C1B18",
  surfaceVariant: "#ECE1C1",
  onSurfaceVariant: "#4D4632",
  outline: "#857A5A",
  outlineVariant: "#D7CEB1",
  surfaceTint: "#F2D28C",
  inverseSurface: "#322F2B",
  inverseOnSurface: "#FBF0E2",
  inversePrimary: "#D5B66E",
});

export const purplePastelLightTheme = createLightTheme({
  primary: "#D3C2F3",
  onPrimary: "#2C1C4A",
  primaryContainer: "#F3EFFF",
  onPrimaryContainer: "#1F1132",
  secondary: "#E2D4F9",
  onSecondary: "#2A1E3E",
  secondaryContainer: "#F7F0FF",
  onSecondaryContainer: "#201333",
  tertiary: "#CEBAF2",
  onTertiary: "#2A1D43",
  tertiaryContainer: "#F4EEFF",
  onTertiaryContainer: "#1C1231",
  background: "#FFFCFF",
  onBackground: "#1B1A1F",
  surface: "#FFFCFF",
  onSurface: "#1B1A1F",
  surfaceVariant: "#E6DFF0",
  onSurfaceVariant: "#4C4458",
  outline: "#8E8598",
  outlineVariant: "#D7CFE3",
  surfaceTint: "#D3C2F3",
  inverseSurface: "#322F36",
  inverseOnSurface: "#F2EDF6",
  inversePrimary: "#B2A0E0",
});

export const mintPastelLightTheme = createLightTheme({
  primary: "#A8E6CF",
  onPrimary: "#00382A",
  primaryContainer: "#DFFAF0",
  onPrimaryContainer: "#103F30",
  secondary: "#B2F1D7",
  onSecondary: "#00382A",
  secondaryContainer: "#D6FBEA",
  onSecondaryContainer: "#134134",
  tertiary: "#95E2D0",
  onTertiary: "#00332B",
  tertiaryContainer: "#D5F8F0",
  onTertiaryContainer: "#0E3D36",
  background: "#FAFFFC",
  onBackground: "#1A1C1A",
  surface: "#FAFFFC",
  onSurface: "#1A1C1A",
  surfaceVariant: "#DAE5DF",
  onSurfaceVariant: "#3F4944",
  outline: "#7C8C86",
  outlineVariant: "#C0CCC6",
  surfaceTint: "#A8E6CF",
  inverseSurface: "#2F312F",
  inverseOnSurface: "#EFF7F1",
  inversePrimary: "#72CBB0",
});

export const lilacPastelLightTheme = createLightTheme({
  primary: "#CDB4DB",
  onPrimary: "#3A2B46",
  primaryContainer: "#F5ECFA",
  onPrimaryContainer: "#432F52",
  secondary: "#E2C9F0",
  onSecondary: "#3C2D4C",
  secondaryContainer: "#F7EAFE",
  onSecondaryContainer: "#452F57",
  tertiary: "#D8C2E0",
  onTertiary: "#352C3F",
  tertiaryContainer: "#F3E7F9",
  onTertiaryContainer: "#422B56",
  background: "#FFFBFF",
  onBackground: "#1D1B20",
  surface: "#FFFBFF",
  onSurface: "#1D1B20",
  surfaceVariant: "#E7E0EC",
  onSurfaceVariant: "#49454F",
  outline: "#7A757F",
  outlineVariant: "#CBC4D0",
  surfaceTint: "#CDB4DB",
  inverseSurface: "#322F35",
  inverseOnSurface: "#F2EDF6",
  inversePrimary: "#A98FC8",
});
